### ISSUE TITLE
Using track name as a secondary option

### ISSUE THREAD

**Issue by ahmetlii** [HeIIow2/music-downloader#11]
I think that the current approach of only using ISRC for YouTube searches is a bit problematic. While it's correct that YouTube finds it out quickly via ISRC, not all songs there have ISRCs (as YouTube cares less about music than, say, Spotify), and sometimes the music just appears on the top through a search of its name. I am also not sure about how music-kraken handles music in different languages - musicbrainz tends to list their transcription - and rather lists its original name as an alias
It would be nice if the scraper searches for the name if both ISRC and Musify fails.

**Comment by HeIIow2** [comment]
Hey,

I totally agree. Currently I am working on restructuring the program. Instead of searching for individual songs it will search for an Artist, then for its Discography and then for each song of each release.

I am telling you. So much work xD. But this approach should be far superior.

On youtube I will use the api's of [invidious](https://invidious.io/) instead of youtube dl for better speed. Then I will use the search pattern `{artist.name} - Topic` and filter for channel. From what I have tried that is really successful. Though obviously I will keep the option to search for the ISRC, because this proved to be very efficient. 

If you wanna help, and maybe Implement the youtube stuff yourself please let me know and I will provide you with more details. This project is realistically to big to release consistent updates for a single person. :3

**Comment by ahmetlii** [comment]
I definitely would like to.

**Comment by HeIIow2** [comment]
I'll update you with a guide <333

**Comment by HeIIow2** [comment]
@ahmetlii I compiled a little [guide for contributing](https://github.com/HeIIow2/music-downloader/blob/master/contribute.md). I suggest you implement the youtube search, I wrote some hopefully helpful comments [here](https://github.com/HeIIow2/music-downloader/blob/master/src/music_kraken/pages/youtube.py).

I hope you can work with this :blue_heart: :white_heart: :blue_heart: :white_heart:
