### ISSUE TITLE
use yt-dlp instead of youtube-dl

### ISSUE THREAD

**Issue by skye-repos** [HeIIow2/music-downloader#15]
yt-dlp doesn't seem to have the same download speed restrictions that youtube-dl does. 

It might even be a drop in replacement?

**Comment by HeIIow2** [comment]
Ohhh sorry for keeping you so long waiting.

I am currently pretty buisy <33
So I am intending to instead use the invidious rest api's.
I don't want something as high level as youtube-dl, because I want to cover so many pages and well.
It would get big quickly, instead I can just use my structure.

For the downloading of the raw audio I might use a library though.
Thanks for your recommendation. I'll keep the issue open.

:heart:

**Comment by HeIIow2** [comment]
Hey, I implemented the YouTube downloader, and I implemented the actual downloading of the video myself without any library.

I used invidious and piped for the metadata. Thank you <33
